#!/usr/bin/env python3
"""Generate a rotating wireframe TORUS or SPHERE for the MC6400 (INS8070).

Geometry is precomputed here and baked as a vertex table; the CPU rotates +
projects (orthographic) each frame and streams an Eulerian-circuit route of the
mesh straight to the X/Y DAC -> one continuous stroke (clean on analog & DSO).
Velocity-based hex-pad control: 4/6 yaw, 2/8 pitch, 5 stop, 0 reset.

Usage:  gen_obj.py torus  asm/torus.asm
        gen_obj.py sphere asm/sphere.asm
"""
import math, sys
from collections import Counter

SINE = [round(64 * math.sin(2 * math.pi * i / 64)) for i in range(64)]


# ---------- geometry ----------
def torus(M=8, N=6, R=32, r=18):
    verts, edges = [], []
    for j in range(M):
        th = 2 * math.pi * j / M
        ct, st = math.cos(th), math.sin(th)
        for k in range(N):
            ph = 2 * math.pi * k / N
            rr = R + r * math.cos(ph)
            verts.append((round(rr * ct), round(r * math.sin(ph)), round(rr * st)))
    for j in range(M):
        for k in range(N):
            v = j * N + k
            edges.append((v, j * N + (k + 1) % N))         # minor ring
            edges.append((v, ((j + 1) % M) * N + k))       # major ring
    return verts, edges


def sphere(M=8, L=4, S=48):
    """M longitudes (even), L latitude rings between the poles."""
    verts, edges = [], []
    for i in range(L):
        beta = math.pi * (i + 1) / (L + 1) - math.pi / 2     # -90..+90
        y = S * math.sin(beta)
        rad = S * math.cos(beta)
        for k in range(M):
            a = 2 * math.pi * k / M
            verts.append((round(rad * math.cos(a)), round(y), round(rad * math.sin(a))))
    north = len(verts); verts.append((0, S, 0))
    south = len(verts); verts.append((0, -S, 0))
    for i in range(L):
        for k in range(M):
            v = i * M + k
            edges.append((v, i * M + (k + 1) % M))           # latitude ring
            if i < L - 1:
                edges.append((v, (i + 1) * M + k))           # vertical
    for k in range(M):
        edges.append((south, 0 * M + k))                     # south cap
        edges.append((north, (L - 1) * M + k))               # north cap
    return verts, edges


def eulerian(nv, edges):
    g = {x: Counter() for x in range(nv)}
    for a, b in edges:
        g[a][b] += 1; g[b][a] += 1
    odd = [x for x in range(nv) if sum(g[x].values()) % 2]
    if odd:
        raise SystemExit("graph not Eulerian (odd-degree vertices: %s)" % odd)
    start = next(x for x in range(nv) if sum(g[x].values()) > 0)
    stack, circ = [start], []
    while stack:
        v = stack[-1]
        if sum(g[v].values()) > 0:
            u = next(n for n in g[v] if g[v][n] > 0)
            g[v][u] -= 1; g[u][v] -= 1
            stack.append(u)
        else:
            circ.append(stack.pop())
    return circ


def db(vals):
    return ', '.join('0x%02X' % (v & 0xFF) for v in vals)


def emit(verts, route, title):
    vlines = "\n".join("        DB    " + db([x, y, z]) for (x, y, z) in verts)
    slines = "\n".join("        DB    " + db(SINE[o:o + 16]) for o in range(0, 64, 16))
    rlines = "\n".join("        DB    " + db(route[o:o + 16]) for o in range(0, len(route), 16))
    return TEMPLATE.format(NVERT=len(verts), NROUTE=len(route), TITLE=title,
                           SINE=slines, VERTS=vlines, ROUTE=rlines)


TEMPLATE = r""";; ============================================================
;;  MC6400 / INS8070  -  {TITLE}  (auto-generated by tools/gen_obj.py)
;;  Orthographic, Eulerian-circuit endpoint streaming, hex-pad control:
;;    4/6 yaw -/+   2/8 pitch -/+   5 stop   0 reset
;; ============================================================
        ORG   0x1000
DAC     EQU   0xE000
KP      EQU   0xFD00
NVERT   EQU   {NVERT}
NROUTE  EQU   {NROUTE}
DAX0    EQU   1
DAY0    EQU   2
AX0     EQU   8
AY0     EQU   5

TMP16   EQU   0xFFC0
VSX     EQU   0xFFC2
VSY     EQU   0xFFC3
ECNT    EQU   0xFFC4
AX      EQU   0xFFC5
AY      EQU   0xFFC6
CAC     EQU   0xFFC7
SAC     EQU   0xFFC8
CBC     EQU   0xFFC9
SBC     EQU   0xFFCA
MA      EQU   0xFFCB
MS      EQU   0xFFCC
MTMP    EQU   0xFFCD
ACC     EQU   0xFFCF
Z1      EQU   0xFFD1
VX      EQU   0xFFD2
VY      EQU   0xFFD3
VZ      EQU   0xFFD4
VCNT    EQU   0xFFD5
DAXV    EQU   0xFFD6
DAYV    EQU   0xFFD7
KEY     EQU   0xFFD8
LASTKEY EQU   0xFFD9
KROW    EQU   0xFFDA
KMASK   EQU   0xFFDB
KVAL    EQU   0xFFDC
SPIN    EQU   0xFFDD          ; heartbeat segment pattern
STACK   EQU   0x13FF

START:  LD    SP,=STACK
        LD    A,=AX0
        ST    A,AX
        LD    A,=AY0
        ST    A,AY
        LD    A,=DAX0
        ST    A,DAXV
        LD    A,=DAY0
        ST    A,DAYV
        LD    A,=0xFF
        ST    A,LASTKEY
        LD    A,=0x01
        ST    A,SPIN
FRAME:  JSR   PROJECT
        LD    P3,=ROUTE
        LD    A,=NROUTE
        ST    A,ECNT
DRLOOP: LD    A,@1(P3)
        JSR   GETVERT
        LD    P2,=DAC
        LD    A,VSX
        ST    A,0(P2)
        LD    A,VSY
        ST    A,1(P2)
        DLD   A,ECNT
        BNZ   DRLOOP
        LD    A,=1
        ST    A,3(P2)
        JSR   HANDLEKEY
        LD    A,AX
        ADD   A,DAXV
        ST    A,AX
        LD    A,AY
        ADD   A,DAYV
        ST    A,AY
        JSR   HEARTB
        BRA   FRAME

; HEARTB: "alive" indicator on display digit 0 (rotates one segment per frame)
HEARTB: LD    P2,=0xFD00
        LD    A,=0x01
        ST    A,0(P2)
        LD    A,SPIN
        SL    A
        BNZ   HBOK
        LD    A,=0x01
HBOK:   ST    A,SPIN
        ST    A,16(P2)
        RET

HANDLEKEY: JSR SCANKEY
        ST    A,KEY
        SUB   A,LASTKEY
        BNZ   HKGO
        RET
HKGO:   LD    A,KEY
        ST    A,LASTKEY
        LD    A,KEY
        SUB   A,=4
        BNZ   HK6
        LD    A,DAYV
        SUB   A,=1
        ST    A,DAYV
        RET
HK6:    LD    A,KEY
        SUB   A,=6
        BNZ   HK2
        LD    A,DAYV
        ADD   A,=1
        ST    A,DAYV
        RET
HK2:    LD    A,KEY
        SUB   A,=2
        BNZ   HK8
        LD    A,DAXV
        SUB   A,=1
        ST    A,DAXV
        RET
HK8:    LD    A,KEY
        SUB   A,=8
        BNZ   HK5
        LD    A,DAXV
        ADD   A,=1
        ST    A,DAXV
        RET
HK5:    LD    A,KEY
        SUB   A,=5
        BNZ   HK0
        LD    A,=0
        ST    A,DAXV
        ST    A,DAYV
        RET
HK0:    LD    A,KEY
        BNZ   HKR
        LD    A,=DAX0
        ST    A,DAXV
        LD    A,=DAY0
        ST    A,DAYV
HKR:    RET

SCANKEY: LD   P2,=KP
        LD    A,=0
        ST    A,KROW
        LD    A,=1
        ST    A,KMASK
SKLP:   LD    A,KMASK
        ST    A,0(P2)
        LD    A,0(P2)
        ST    A,KVAL
        AND   A,=1
        BNZ   SK8F
        LD    A,KROW
        RET
SK8F:   LD    A,KVAL
        AND   A,=2
        BNZ   SKNX
        LD    A,KROW
        ADD   A,=8
        RET
SKNX:   LD    A,KMASK
        SL    A
        ST    A,KMASK
        LD    A,KROW
        ADD   A,=1
        ST    A,KROW
        SUB   A,=8
        BNZ   SKLP
        LD    A,=0xFF
        RET

PROJECT: LD   A,AY
        JSR   SINLK
        ST    A,SBC
        LD    A,AY
        ADD   A,=16
        JSR   SINLK
        ST    A,CBC
        LD    A,AX
        JSR   SINLK
        ST    A,SAC
        LD    A,AX
        ADD   A,=16
        JSR   SINLK
        ST    A,CAC
        LD    A,=NVERT
        ST    A,VCNT
        LD    P3,=VERTS
        LD    P2,=PCOORD
PVLOOP: JSR   PROJ1
        DLD   A,VCNT
        BNZ   PVLOOP
        RET

PROJ1:  LD    A,@1(P3)
        ST    A,VX
        LD    A,@1(P3)
        ST    A,VY
        LD    A,@1(P3)
        ST    A,VZ
        LD    A,VX
        ST    A,MA
        LD    A,CBC
        ST    A,MS
        JSR   MULFIX
        ST    EA,ACC
        LD    A,VZ
        ST    A,MA
        LD    A,SBC
        ST    A,MS
        JSR   MULFIX
        ADD   EA,ACC
        ADD   EA,=128
        ST    A,@1(P2)
        LD    A,VZ
        ST    A,MA
        LD    A,CBC
        ST    A,MS
        JSR   MULFIX
        ST    EA,ACC
        LD    A,VX
        ST    A,MA
        LD    A,SBC
        ST    A,MS
        JSR   MULFIX
        ST    EA,MTMP
        LD    EA,ACC
        SUB   EA,MTMP
        ST    A,Z1
        LD    A,VY
        ST    A,MA
        LD    A,CAC
        ST    A,MS
        JSR   MULFIX
        ST    EA,ACC
        LD    A,Z1
        ST    A,MA
        LD    A,SAC
        ST    A,MS
        JSR   MULFIX
        ST    EA,MTMP
        LD    EA,ACC
        SUB   EA,MTMP
        ADD   EA,=128
        ST    A,@1(P2)
        RET

MULFIX: LD    A,=0
        LD    E,A
        LD    A,MS
        BP    MK1
        LD    A,=0xFF
        LD    E,A
        LD    A,MS
MK1:    LD    T,EA
        LD    A,=0
        LD    E,A
        LD    A,MA
        BP    MK2
        LD    A,=0xFF
        LD    E,A
        LD    A,MA
MK2:    MPY   EA,T
        LD    EA,T
        ADD   EA,=0x8000
        SR    EA
        SR    EA
        SR    EA
        SR    EA
        SR    EA
        SR    EA
        SUB   EA,=0x200
        RET

SINLK:  AND   A,=0x3F
        ST    A,TMP16
        LD    A,=0
        ST    A,TMP16+1
        LD    EA,=SINE
        ADD   EA,TMP16
        LD    P2,EA
        LD    A,0(P2)
        RET

GETVERT: SL   A
        ST    A,TMP16
        LD    A,=0
        ST    A,TMP16+1
        LD    EA,=PCOORD
        ADD   EA,TMP16
        LD    P2,EA
        LD    A,0(P2)
        ST    A,VSX
        LD    A,1(P2)
        ST    A,VSY
        RET

SINE:
{SINE}
VERTS:
{VERTS}
ROUTE:
{ROUTE}
PCOORD: DS    NVERT+NVERT
"""

if __name__ == "__main__":
    kind = sys.argv[1] if len(sys.argv) > 1 else "torus"
    out = sys.argv[2] if len(sys.argv) > 2 else "asm/%s.asm" % kind
    if kind == "torus":
        verts, edges = torus()
        title = "ROTATING WIREFRAME TORUS"
    elif kind == "sphere":
        verts, edges = sphere()
        title = "ROTATING WIREFRAME SPHERE"
    else:
        raise SystemExit("kind must be torus or sphere")
    route = eulerian(len(verts), edges)
    open(out, "w").write(emit(verts, route, title))
    print("wrote %s  (%s: %d verts, %d edges, route %d)" %
          (out, kind, len(verts), len(edges), len(route)))
